blueprint:
  name: Urlaub & Anwesenheitssimulation (Jalousien + Licht + Wetter + Notify)
  description: >
    Simuliert Anwesenheit während des Urlaubs:
    - Jalousien morgens öffnen und abends schließen – mit zufälligem Start innerhalb eines Zeitfensters und einstellbarer Pause zwischen den Jalousien.
    - Optionale Wetterlogik: Tagsüber automatisch schließen (z. B. bei Hitze/starker Sonne) und optional wieder öffnen.
    - Abends Licht zufällig einschalten (Dauer zufällig im Rahmen) – für realistische Anwesenheit.
    - Optional: Benachrichtigungen via notify.*-Service (z. B. Telegram).
    - Aktivierung über ein (Urlaubs-)Input-Boolean/Helper.

  domain: automation
  author: chatgpt
  homeassistant:
    min_version: 2023.6.0

  input:
    vacation_helper:
      name: Urlaubs/Umschalt-Helfer (Input Boolean)
      selector:
        entity:
          domain: input_boolean

    covers_morning:
      name: Jalousien für morgens (öffnen)
      selector:
        target:
          entity:
            domain: cover
      default: []

    covers_evening:
      name: Jalousien für abends (schließen)
      selector:
        target:
          entity:
            domain: cover
      default: []

    cover_gap_seconds:
      name: Wartezeit zwischen Jalousien (Sekunden)
      selector:
        number:
          min: 0
          max: 900
          step: 5
          mode: slider
          unit_of_measurement: s
      default: 30

    morning_window_start:
      name: Morgen-Zeitfenster Anfang
      selector: { time: {} }
      default: "07:00:00"
    morning_window_end:
      name: Morgen-Zeitfenster Ende
      selector: { time: {} }
      default: "07:30:00"

    evening_window_start:
      name: Abend-Zeitfenster Anfang
      selector: { time: {} }
      default: "20:00:00"
    evening_window_end:
      name: Abend-Zeitfenster Ende
      selector: { time: {} }
      default: "21:00:00"

    enable_day_weather_close:
      name: Tagsüber per Wetter schließen
      selector: { boolean: {} }
      default: false

    weather_covers:
      name: Jalousien für Wetter-Logik
      selector:
        target:
          entity:
            domain: cover
      default: []

    weather_entity:
      name: Wetter-Entity (weather.*) – optional
      selector:
        entity:
          domain: weather
      default: ""

    outdoor_temp:
      name: Außentemperatur-Sensor – optional
      selector:
        entity:
          domain: sensor
      default: ""

    illuminance_sensor:
      name: Helligkeit/Lux-Sensor – optional
      selector:
        entity:
          domain: sensor
      default: ""

    temp_close_threshold:
      name: Schließen ab Temperatur (°C)
      selector:
        number:
          min: 10
